apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: jenkins
  namespace: argocd
spec:
  project: monitoring-stack
  source:
    repoURL: https://charts.jenkins.io
    chart: jenkins
    targetRevision: 5.1.16 # Use latest stable or pin as needed
    helm:
      values: |
        controller:
          adminUser: admin
          adminPassword: admin123
          serviceType: LoadBalancer
          installPlugins:
            - kubernetes:latest
            - workflow-aggregator:latest
            - git:latest
            - configuration-as-code:latest
          resources:
            requests:
              cpu: 500m
              memory: 1Gi
            limits:
              cpu: 1
              memory: 2Gi
  destination:
    server: https://kubernetes.default.svc
    namespace: jenkins
  syncPolicy:
    automated:
      selfHeal: true
      prune: true
