apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: monitoring-secrets
  namespace: argocd
spec:
  project: monitoring-stack
  source:
    repoURL: git@github.com:StanislavYermolenko/terraform-aks-argocd.git
    targetRevision: HEAD
    path: gitops-config/manifests/monitoring-secrets
  destination:
    server: https://kubernetes.default.svc
    namespace: monitoring
  syncPolicy:
    automated:
      selfHeal: true
      prune: true
    syncOptions:
      - CreateNamespace=false  # Namespace created by Terraform
