apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: prometheus
  namespace: argocd
spec:
  project: monitoring-stack
  source:
    repoURL: https://prometheus-community.github.io/helm-charts
    chart: kube-prometheus-stack
    targetRevision: 51.2.0
    helm:
      values: |
        fullnameOverride: prometheus
        # Disable CRDs since we install them manually
        crds:
          enabled: false
        # Disable components that might cause issues
        prometheusOperator:
          admissionWebhooks:
            enabled: false
          thanosImage:
            tag: ""
        prometheus:
          prometheusSpec:
            retention: 7d
            resources:
              requests:
                memory: 400Mi
                cpu: 200m
            storageSpec:
              volumeClaimTemplate:
                spec:
                  storageClassName: managed-csi
                  accessModes: ["ReadWriteOnce"]
                  resources:
                    requests:
                      storage: 10Gi
        grafana:
          enabled: true
          admin:
            existingSecret: ""
            userKey: admin-user
            passwordKey: admin-password
          persistence:
            enabled: true
            storageClassName: managed-csi
            size: 5Gi
          service:
            type: ClusterIP
          ingress:
            enabled: false
        alertmanager:
          enabled: true
          alertmanagerSpec:
            storage:
              volumeClaimTemplate:
                spec:
                  storageClassName: managed-csi
                  accessModes: ["ReadWriteOnce"]
                  resources:
                    requests:
                      storage: 5Gi
        nodeExporter:
          enabled: true
        kubeStateMetrics:
          enabled: true
  destination:
    server: https://kubernetes.default.svc
    namespace: monitoring
  syncPolicy:
    automated:
      selfHeal: true
      prune: true
