global:
  logging:
    level: info

server:
  service:
    type: LoadBalancer
  extraArgs:
    - --insecure
  config:
    # Disable admin user generation (we'll use Key Vault)
    admin.enabled: "true"
  # We'll manage the admin secret separately through Kubernetes secret
  
repoServer:
  replicas: 1

controller:
  replicas: 1

redis:
  enabled: true

dex:
  enabled: false

notifications:
  enabled: false

applicationSet:
  enabled: true
