apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: github-credentials
  namespace: jenkins
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: azure-keyvault-secret-store
    kind: SecretStore
  target:
    name: github-credentials
    creationPolicy: Owner
  data:
    - secretKey: GITHUB_USERNAME
      remoteRef:
        key: github-username
    - secretKey: GITHUB_TOKEN
      remoteRef:
        key: github-token
