apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: docker-apps
  namespace: argocd
spec:
  description: Docker workloads via GitOps
  sourceRepos:
    - https://github.com/StanislavYermolenko/gitops-config
    - git@github.com:StanislavYermolenko/gitops-config.git
  destinations:
    - namespace: demo-app
      server: https://kubernetes.default.svc

  clusterResourceWhitelist: []

  namespaceResourceWhitelist: 
    - group: apps               
      kind: Deployment
    - group: ""                 
      kind: Service
