apiVersion: apps/v1
kind: Deployment
metadata:
  name: myapp
  namespace: demo-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: myapp
  template:
    metadata:
      labels:
        app: myapp
    spec:
      containers:
        - name: myapp
          image: ghcr.io/stanislavyermolenko/myapp:v1
          ports:
            - containerPort: 80
