apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: gitops-projects
  namespace: argocd
spec:
  project: default
  source:
    repoURL: git@github.com:StanislavYermolenko/gitops-config.git
    targetRevision: master
    path: projects
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd
  syncPolicy:
    automated:
      prune: true
      selfHeal: true

