apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: gitops-projects
  namespace: argocd
spec:
  project: default
  source:
    repoURL: git@github.com:StanislavYermolenko/terraform-aks-argocd.git
    targetRevision: HEAD
    path: gitops-config/projects
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: monitoring-stack
  namespace: argocd
spec:
  project: default
  source:
    repoURL: git@github.com:StanislavYermolenko/terraform-aks-argocd.git
    targetRevision: HEAD
    path: gitops-config/apps
    directory:
      include: "{prometheus,grafana,loki,promtail}.yaml"
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd
  syncPolicy:
    automated:
      selfHeal: true
      prune: true
    syncOptions:
      - CreateNamespace=true

